Repository Chance-Glance/server, pull requests merged in 2024-10, with the labels that each got.

#9 엔티티 작성 완료
  build.gradle
  src/main/java/com/example/mohago_nocar/course/application/CourseService.java
  src/main/java/com/example/mohago_nocar/course/domain/model/course/Course.java
  src/main/java/com/example/mohago_nocar/course/domain/model/routeStep/RouteStep.java
  src/main/java/com/example/mohago_nocar/course/domain/model/travelSpot/AttractionSpot.java
  src/main/java/com/example/mohago_nocar/course/domain/model/travelSpot/RestaurantSpot.java
  src/main/java/com/example/mohago_nocar/course/domain/model/travelSpot/TravelSpot.java
  src/main/java/com/example/mohago_nocar/course/domain/model/vo/Location.java
  src/main/java/com/example/mohago_nocar/course/domain/repository/CourseRepository.java
  src/main/java/com/example/mohago_nocar/course/domain/repository/RouteStepRepository.java
  src/main/java/com/example/mohago_nocar/course/domain/repository/TravelSpotRepository.java
  src/main/java/com/example/mohago_nocar/course/domain/service/CourseUseCase.java
  src/main/java/com/example/mohago_nocar/course/infrastructure/course/CourseJpaRepository.java
  src/main/java/com/example/mohago_nocar/course/infrastructure/course/CourseRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/course/infrastructure/routeStep/RouteStepJpaRepository.java
  src/main/java/com/example/mohago_nocar/course/infrastructure/routeStep/RouteStepRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/course/infrastructure/travelSpot/TravelSpotJpaRepository.java
  src/main/java/com/example/mohago_nocar/course/infrastructure/travelSpot/TravelSpotRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/course/presentation/CourseController.java
  src/main/java/com/example/mohago_nocar/festival/application/FestivalService.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/Festival.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/FestivalImage.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/vo/ActivePeriod.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/vo/Address.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/vo/Location.java
  src/main/java/com/example/mohago_nocar/festival/domain/repository/FestivalRepository.java
  src/main/java/com/example/mohago_nocar/festival/domain/service/FestivalUseCase.java
  src/main/java/com/example/mohago_nocar/festival/infrastructure/FestivalJpaRepository.java
  src/main/java/com/example/mohago_nocar/festival/infrastructure/FestivalRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/festival/presentation/FestivalController.java
  src/main/java/com/example/mohago_nocar/global/common/domain/BaseEntity.java
  src/main/java/com/example/mohago_nocar/global/util/DurationToIntervalConverter.java
Labels: :safety_vest: setting

#12 setting: 스웨거 세팅 완료
  build.gradle
  src/main/java/com/example/mohago_nocar/global/config/SwaggerConfig.java
Labels: :safety_vest: setting

#13 전국 축제 조회 API 작성 완료
  src/main/java/com/example/mohago_nocar/festival/application/FestivalImageService.java
  src/main/java/com/example/mohago_nocar/festival/application/FestivalService.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/Festival.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/vo/ActivePeriod.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/vo/Address.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/vo/Location.java
  src/main/java/com/example/mohago_nocar/festival/domain/repository/FestivalImageRepository.java
  src/main/java/com/example/mohago_nocar/festival/domain/repository/FestivalRepository.java
  src/main/java/com/example/mohago_nocar/festival/domain/service/FestivalImageUseCase.java
  src/main/java/com/example/mohago_nocar/festival/domain/service/FestivalUseCase.java
  src/main/java/com/example/mohago_nocar/festival/infrastructure/FestivalImageJpaRepository.java
  src/main/java/com/example/mohago_nocar/festival/infrastructure/FestivalImageRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/festival/infrastructure/FestivalRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/festival/presentation/FestivalController.java
  src/main/java/com/example/mohago_nocar/festival/presentation/response/FestivalResponseDto.java
  src/main/java/com/example/mohago_nocar/global/common/dto/PagedResponseDto.java
  src/main/java/com/example/mohago_nocar/global/common/exception/Body.java
  src/main/java/com/example/mohago_nocar/global/common/exception/CustomException.java
  src/main/java/com/example/mohago_nocar/global/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/mohago_nocar/global/common/exception/GlobalStatus.java
  src/main/java/com/example/mohago_nocar/global/common/exception/Status.java
  src/main/java/com/example/mohago_nocar/global/common/response/ApiResponse.java
  src/main/resources/application-dev.yml
Labels: :seedling: feat

#14 장소 간의 이동정보 검색 기능 구현 완료
  build.gradle
  src/main/java/com/example/mohago_nocar/course/domain/model/routeStep/RouteStep.java
  src/main/java/com/example/mohago_nocar/course/domain/model/vo/Location.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/Festival.java
  src/main/java/com/example/mohago_nocar/global/common/domain/vo/Location.java
  src/main/java/com/example/mohago_nocar/global/config/RestClientConfig.java
  src/main/java/com/example/mohago_nocar/transit/application/service/TransitService.java
  src/main/java/com/example/mohago_nocar/transit/domain/model/BusPath.java
  src/main/java/com/example/mohago_nocar/transit/domain/model/PathType.java
  src/main/java/com/example/mohago_nocar/transit/domain/model/SubPath.java
  src/main/java/com/example/mohago_nocar/transit/domain/model/SubwayPath.java
  src/main/java/com/example/mohago_nocar/transit/domain/model/TransitInfo.java
  src/main/java/com/example/mohago_nocar/transit/domain/model/WalkPath.java
  src/main/java/com/example/mohago_nocar/transit/domain/service/TransitUseCase.java
  src/main/java/com/example/mohago_nocar/transit/infrastructure/externalApi/ODsayApiClient.java
  src/main/java/com/example/mohago_nocar/transit/infrastructure/externalApi/dto/OdsayResponse.java
  src/main/java/com/example/mohago_nocar/transit/infrastructure/mapper/OdsayResponseDeserializer.java
  src/main/java/com/example/mohago_nocar/transit/infrastructure/mapper/TransitPathMapper.java
  src/main/resources/application-dev.yml
Labels: :seedling: feat

#16 import 오류 해결 완료
  src/main/java/com/example/mohago_nocar/festival/presentation/response/FestivalResponseDto.java
Labels: :lady_beetle: bug

#19 축제 주변 장소 저장 기능 구현 완료
  src/main/java/com/example/mohago_nocar/festival/application/FestivalService.java
  src/main/java/com/example/mohago_nocar/festival/domain/repository/FestivalRepository.java
  src/main/java/com/example/mohago_nocar/festival/domain/service/FestivalUseCase.java
  src/main/java/com/example/mohago_nocar/festival/infrastructure/FestivalRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/festival/presentation/exception/FestivalExceptionCode.java
  src/main/java/com/example/mohago_nocar/festival/presentation/exception/FestivalNotFoundException.java
  src/main/java/com/example/mohago_nocar/festival/presentation/response/FestivalLocationResponseDto.java
  src/main/java/com/example/mohago_nocar/global/common/domain/vo/Location.java
  src/main/java/com/example/mohago_nocar/global/common/exception/CustomException.java
  src/main/java/com/example/mohago_nocar/global/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/mohago_nocar/place/application/PlaceService.java
  src/main/java/com/example/mohago_nocar/place/application/mapper/FestivalNearPlaceMapper.java
  src/main/java/com/example/mohago_nocar/place/domain/model/FestivalNearPlace.java
  src/main/java/com/example/mohago_nocar/place/domain/model/FestivalNearPlaceImage.java
  src/main/java/com/example/mohago_nocar/place/domain/model/OperatingSchedule.java
  src/main/java/com/example/mohago_nocar/place/domain/model/PlaceType.java
  src/main/java/com/example/mohago_nocar/place/domain/repository/FestivalNearPlaceImageRepository.java
  src/main/java/com/example/mohago_nocar/place/domain/repository/FestivalNearPlaceRepository.java
  src/main/java/com/example/mohago_nocar/place/domain/service/PlaceUseCase.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceImageJpaRepository.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceImageRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceJpaRepository.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/GoogleApiClient.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/dto/request/GoogleNearPlaceRequest.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/dto/request/LocationRestriction.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/dto/response/GoogleNearbyPlaceResponse.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/dto/response/GooglePlaceImageResponse.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/dto/response/PlaceResponseDto.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/mapper/GooglePlaceMapper.java
  src/main/java/com/example/mohago_nocar/place/presentation/PlaceController.java
  src/main/resources/application-dev.yml
Labels: :seedling: feat

#24 feat: 축제 주변 장소 조회 API 작성 완료 #22
  src/main/java/com/example/mohago_nocar/festival/application/FestivalService.java
  src/main/java/com/example/mohago_nocar/festival/domain/service/FestivalUseCase.java
  src/main/java/com/example/mohago_nocar/place/application/PlaceService.java
  src/main/java/com/example/mohago_nocar/place/domain/repository/FestivalNearPlaceImageRepository.java
  src/main/java/com/example/mohago_nocar/place/domain/repository/FestivalNearPlaceRepository.java
  src/main/java/com/example/mohago_nocar/place/domain/service/PlaceUseCase.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceImageJpaRepository.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceImageRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceJpaRepository.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/GoogleApiClient.java
  src/main/java/com/example/mohago_nocar/place/presentation/NearPlaceResponseDto.java
  src/main/java/com/example/mohago_nocar/place/presentation/PlaceController.java
Labels: :seedling: feat

#23 Feat/#18 축제 일정 조회 API
  src/main/java/com/example/mohago_nocar/festival/application/FestivalService.java
  src/main/java/com/example/mohago_nocar/festival/domain/service/FestivalUseCase.java
  src/main/java/com/example/mohago_nocar/festival/presentation/FestivalController.java
  src/main/java/com/example/mohago_nocar/festival/presentation/response/FestivalActivePeriodResponseDto.java
Labels: :seedling: feat

#30 여행 코스 설계 API 구현 완료
  src/main/java/com/example/mohago_nocar/festival/application/FestivalService.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/Festival.java
  src/main/java/com/example/mohago_nocar/festival/domain/model/vo/ActivePeriod.java
  src/main/java/com/example/mohago_nocar/festival/domain/repository/FestivalRepository.java
  src/main/java/com/example/mohago_nocar/festival/infrastructure/FestivalRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/global/common/domain/vo/Location.java
  src/main/java/com/example/mohago_nocar/global/common/exception/EntityNotFoundException.java
  src/main/java/com/example/mohago_nocar/global/common/exception/InvalidValueException.java
  src/main/java/com/example/mohago_nocar/place/domain/repository/FestivalNearPlaceRepository.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceJpaRepository.java
  src/main/java/com/example/mohago_nocar/place/infrastructure/FestivalNearPlaceRepositoryImpl.java
  src/main/java/com/example/mohago_nocar/place/presentation/exception/PlaceErrorCode.java
  src/main/java/com/example/mohago_nocar/plan/application/TravelPlanService.java
  src/main/java/com/example/mohago_nocar/plan/domain/service/TravelPlanUseCase.java
  src/main/java/com/example/mohago_nocar/plan/presentation/TravelPlanController.java
  src/main/java/com/example/mohago_nocar/plan/presentation/exception/PlanErrorCode.java
  src/main/java/com/example/mohago_nocar/plan/presentation/request/PlanTravelCourseRequestDto.java
  src/main/java/com/example/mohago_nocar/plan/presentation/response/BusPathResponseDto.java
  src/main/java/com/example/mohago_nocar/plan/presentation/response/PlanTravelCourseResponseDto.java
  src/main/java/com/example/mohago_nocar/plan/presentation/response/SubPathResponseDto.java
  src/main/java/com/example/mohago_nocar/plan/presentation/response/SubwayPathResponseDto.java
  src/main/java/com/example/mohago_nocar/plan/presentation/response/WalkPathResponseDto.java
  src/main/java/com/example/mohago_nocar/transit/application/mapper/TransitMapper.java
  src/main/java/com/example/mohago_nocar/transit/domain/model/TransitInfo.java
  src/main/java/com/example/mohago_nocar/transit/infrastructure/error/code/OdsayErrorCode.java
  src/main/java/com/example/mohago_nocar/transit/infrastructure/error/exception/OdsayDistanceException.java
  src/main/java/com/example/mohago_nocar/transit/infrastructure/externalApi/ODsayApiClient.java
  src/main/java/com/example/mohago_nocar/transit/infrastructure/mapper/OdsayRouteMapper.java
Labels: :seedling: feat

#29 위, 경도 매핑 오류 수정 완료
  src/main/java/com/example/mohago_nocar/place/infrastructure/externalApi/GoogleApiClient.java
Labels: :lady_beetle: bug
